services:
  postgres:
    container_name: bookings
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookings
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data